# Generated by Django 6.0.2 on 2026-03-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('date', models.DateTimeField(verbose_name='Дата события')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Фото события')),
            ],
        ),
    ]
