# Generated by Django 6.0.5 on 2026-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateField(default='2026-07-04', verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, default='Вход свободный', max_length=100, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='event',
            name='source_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на источник'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание события'),
        ),
    ]
