# Generated by Django 6.0.5 on 2026-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_date_event_date_end_event_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(blank=True, default='Вход свободный', max_length=100, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='event',
            name='source_link',
            field=models.URLField(blank=True, verbose_name='Подробнее по ссылке'),
        ),
    ]
