# Generated by Django 6.0.3 on 2026-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_note_options_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='Удалена'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О пользователе'),
        ),
    ]
