# Generated by Django 6.0.3 on 2026-04-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_note_removed_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
