# Generated by Django 6.0.4 on 2026-05-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур ', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterModelOptions(
            name='tourplace',
            options={'verbose_name': 'Место тура', 'verbose_name_plural': 'Места тура'},
        ),
    ]
