# Generated by Django 6.0.5 on 2026-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('culture', 'Культура и история'), ('religion', 'Религия'), ('nature', 'Отдых на природе'), ('visit', 'Визит-центры')], max_length=50, verbose_name='Категория')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_time', models.CharField(blank=True, max_length=100, verbose_name='Часы работы')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Стоимость')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='guide/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Путеводитель',
            },
        ),
    ]
