# Generated by Django 6.0.5 on 2026-07-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_guideplace_latitude_guideplace_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideplace',
            name='phone',
            field=models.CharField(blank=True, help_text='Например: +7 (391) 227-92-04', max_length=100, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='guideplace',
            name='website',
            field=models.URLField(blank=True, help_text='Ссылка на официальный сайт', verbose_name='Сайт'),
        ),
    ]
